(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control12_vuqSWd: function (elem) {
      return elem.textContent;
    },
    doAction_uiControl12_ckrmMA: function (data, elem) {},
    getTemplate_uiControl12_ckrmMA: function () {
      var selfTemplate = "import { Header } from 'ysp-interior-components';\n\nexport default class extends React.Component{\n  constructor(props){\n    super(props);\n  }\n  render() {\n    var data=this.props.customData;\n    return (\n      <div>\n        <Header title={data} />\n      </div>\n    )\n  }\n}";
      return "'use strict';\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if (\"value\" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nvar _yspInteriorComponents = require('ysp-interior-components');\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError(\"Cannot call a class as a function\"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError(\"this hasn't been initialised - super() hasn't been called\"); } return call && (typeof call === \"object\" || typeof call === \"function\") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== \"function\" && superClass !== null) { throw new TypeError(\"Super expression must either be null or a function, not \" + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _class = function (_React$Component) {\n  _inherits(_class, _React$Component);\n\n  function _class(props) {\n    _classCallCheck(this, _class);\n\n    return _possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).call(this, props));\n  }\n\n  _createClass(_class, [{\n    key: 'render',\n    value: function render() {\n      var data = this.props.customData;\n      return React.createElement(\n        'div',\n        null,\n        React.createElement(_yspInteriorComponents.Header, { title: data })\n      );\n    }\n  }]);\n\n  return _class;\n}(React.Component);\n\nexports.default = _class;";
    },
    getData_control13_9Li90b: function (elem) {
      var arr = [];var arr1 = [];var data = [];var tits = elem.querySelectorAll('h5');for (var i = 0; i < tits.length; i++) {
        arr.push(tits[i].textContent);
      }var cons = elem.querySelectorAll('p');for (var i = 0; i < cons.length; i++) {
        arr1.push(cons[i].textContent);
      }for (var i = 0; i < arr.length; i++) {
        var obj = {};for (var j = 0; j < arr1.length; j++) {
          if (i == j) {
            obj.title = arr[i];obj.con = arr1[j];data.push(obj);
          }
        }
      } // data[1].con.split('\n\t\t\t\t\t\t').shift();
      // data[2].con.split('\n\t\t\t\t\t\t').shift();
      return data;
    },
    doAction_uiControl13_5sKTkI: function (data, elem) {},
    getTemplate_uiControl13_5sKTkI: function () {
      var selfTemplate = "export default class extends React.Component{\n  constructor(props){\n    super(props);\n  }\n  render() {\n    var data=this.props.customData;\n    return (\n      <div className='registration-protocol-con'>\n        {\n          data && data.map((item,i)=>(\n            <div>\n              <h5>{item.title}</h5>\n              <p>{item.con}</p>\n            </div>\n          ))\n        }\n      </div>\n    )\n  }\n}";
      return "'use strict';\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if (\"value\" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError(\"Cannot call a class as a function\"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError(\"this hasn't been initialised - super() hasn't been called\"); } return call && (typeof call === \"object\" || typeof call === \"function\") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== \"function\" && superClass !== null) { throw new TypeError(\"Super expression must either be null or a function, not \" + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _class = function (_React$Component) {\n  _inherits(_class, _React$Component);\n\n  function _class(props) {\n    _classCallCheck(this, _class);\n\n    return _possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).call(this, props));\n  }\n\n  _createClass(_class, [{\n    key: 'render',\n    value: function render() {\n      var data = this.props.customData;\n      return React.createElement(\n        'div',\n        { className: 'registration-protocol-con' },\n        data && data.map(function (item, i) {\n          return React.createElement(\n            'div',\n            null,\n            React.createElement(\n              'h5',\n              null,\n              item.title\n            ),\n            React.createElement(\n              'p',\n              null,\n              item.con\n            )\n          );\n        })\n      );\n    }\n  }]);\n\n  return _class;\n}(React.Component);\n\nexports.default = _class;";
    }
  }, "registrationProtocol");
})(window, ysp);