(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control37_R4UXaN: function (elem) {
      if (!elem) {
        return;
      }return { title: elem.querySelector('h3').textContent, text: elem.querySelector('.zc_status_txt').textContent, btn: elem.querySelector('a').textContent };
    },
    doAction_uiControl26_uNlbGQ: function (data, elem) {
      if (data.eventType == 'backIndex') {
        elem.querySelector('a').click();
      }
    },
    getTemplate_uiControl26_uNlbGQ: function () {
      var selfTemplate = "export default class extends React.Component{\n  constructor(props){\n    super(props);\n  }\n  backIndex=(e)=>{\n    var target=e.target;\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:\"backIndex\"\n      })\n    }\n  }\n  render() {\n    var data=this.props.customData;\n    return (\n      <div>\n        <i className='success-img'></i>\n        <h3>{data && data.title}</h3>\n        <p>{data && data.text}</p>\n        <button onClick={this.backIndex}>{data && data.btn}</button>\n      </div>\n    )\n  }\n}";
      return '"use strict";\n\nObject.defineProperty(exports, "__esModule", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn\'t been initialised - super() hasn\'t been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _class = function (_React$Component) {\n  _inherits(_class, _React$Component);\n\n  function _class(props) {\n    _classCallCheck(this, _class);\n\n    var _this = _possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).call(this, props));\n\n    _this.backIndex = function (e) {\n      var target = e.target;\n      var handler = _this.props.customHandler;\n      if (handler) {\n        handler({\n          eventType: "backIndex"\n        });\n      }\n    };\n\n    return _this;\n  }\n\n  _createClass(_class, [{\n    key: "render",\n    value: function render() {\n      var data = this.props.customData;\n      return React.createElement(\n        "div",\n        null,\n        React.createElement("i", { className: "success-img" }),\n        React.createElement(\n          "h3",\n          null,\n          data && data.title\n        ),\n        React.createElement(\n          "p",\n          null,\n          data && data.text\n        ),\n        React.createElement(\n          "button",\n          { onClick: this.backIndex },\n          data && data.btn\n        )\n      );\n    }\n  }]);\n\n  return _class;\n}(React.Component);\n\nexports.default = _class;';
    }
  }, "registeredSuccessfully");
})(window, ysp);